Moovi/Models/ErrorViewModel.cs
namespace Moovi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Moovi/Models/Movie.cs
using System.ComponentModel.DataAnnotations;

namespace Moovi.Models
{
    public class Movie
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage ="Title is required")]
        public string Title { get; set; }
        public string? FileName { get; set; }
        public string? FilePath { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifyDate { get; set; }
    }
}

Moovi/ViewModels/AdminMovieDetailViewModel.cs
namespace Moovi.ViewModels
{
    public class AdminMovieDetailViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string? FileName { get; set; }
        public string? FilePath { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifyDate { get; set; }
    }
}

Moovi/ViewModels/AdminMovieViewModel.cs
namespace Moovi.ViewModels
{
    public class AdminMovieViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string? FileName { get; set; }
        public string? FilePath { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifyDate { get; set; }
    }
}

Moovi/ViewModels/MoviesViewModel.cs
namespace Moovi.ViewModels
{
    public class MoviesViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string? FileName { get; set; }
        public string? FilePath { get; set; }
    }
}

Moovi/ViewModels/UpsertMovieViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Moovi.ViewModels
{
    public class UpsertMovieViewModel
    {
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Title is require!")]
        public string Title { get; set; }
        public string? FileName { get; set; }
        public string? FilePath { get; set; }
        public IFormFile? Formfile { get; set; }
    }
}

Moovi/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using Moovi.Services.Interfaces;
using Moovi.ViewModels;
using System;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace Moovi.Controllers
{
    public class AdminController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IHostingEnvironment _environment;

        public AdminController(IHostingEnvironment environment, IMovieService movieService)
        {
            _movieService = movieService;
            _environment = environment;
        }

        public IActionResult Index()
        {
            var adminMovies = _movieService.GetAdminMovies();
            // manipulate file path
            adminMovies = adminMovies.Select(m =>
            {
                m.FilePath = "~/uploads/movies/avatar2.jpg";
                return m;
            }).ToList();

            return View(adminMovies);
        }
        public IActionResult DetailMovie(Guid id)
        {
            var adminDetailMovie = _movieService.GetMovie(id);
            return View(adminDetailMovie);
        }
        public IActionResult UpsertMovie(Guid? id)
        {
            if (id.HasValue)
            {
                var existingMovie = _movieService.GetMovie(id.Value);
                var formMovie = new UpsertMovieViewModel()
                {
                    Id = id.Value,
                    Title = existingMovie.Title,
                    FileName = existingMovie.FileName,
                    FilePath = existingMovie.FilePath
                };
                return View(formMovie);
            }
            else
            {
                var formMovie = new UpsertMovieViewModel()
                {
                    Id = Guid.Empty,
                    Title = ""
                };
                return View(formMovie);

            }
        }

        [HttpPost]
        public IActionResult UpsertMovie(UpsertMovieViewModel upsertMovie)
        {
            if (ModelState.IsValid)
            {
                if(upsertMovie.Formfile != null)
                    UploadMovieImage(upsertMovie.Formfile);

                _movieService.UpsertMovie(upsertMovie.Id, upsertMovie);
                
                return RedirectToAction(nameof(Index));
            }
            return View(upsertMovie);
        }
        public IActionResult DeleteMovie(Guid id)
        {
            _movieService.DeleteMovie(id);
            return RedirectToAction(nameof(Index));
        }

        private void UploadMovieImage(IFormFile targetFile) 
        {
            string wwwPath = _environment.WebRootPath;
            string path = Path.Combine(wwwPath, "uploads/movies");

            // upload file in folder
            string fileName = Path.GetFileName(targetFile.FileName);
            using (FileStream strem = new FileStream(Path.Combine(path, fileName), FileMode.Create))
            {
                targetFile.CopyTo(strem);

            }
        }
    }
}

Moovi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Moovi.Models;
using System.Diagnostics;

namespace Moovi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Moovi/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Moovi.Services.Interfaces;

namespace Moovi.Controllers
{
    public class MovieController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IMovieService _movieService;

        public MovieController(IWebHostEnvironment webHostEnvironment, IMovieService movieService) 
        {
            _movieService = movieService;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var moviesView = _movieService.GetMovies();

            // manipulate file path
            moviesView = moviesView.Select(m =>
            {
                m.FilePath = "~/uploads/movies/avatar2.jpg";
                return m;
            }).ToList();
            return View(moviesView);
        }
    }
}

Moovi/Pages/Ying.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Moovi.Pages
{
    public class YingModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Moovi/Pages/Ying.cshtml
@page
@model Moovi.Pages.YingModel
@{
}

Moovi/Views/Admin/CreateMovie.cshtml
@using Moovi.ViewModels
@{
    UpsertMovieViewModel formMovie = (UpsertMovieViewModel)ViewData["FormMovie"];
}
<div class="container">
    <div class="row my-4">
        <h1>Create Movie</h1>
        <a class="link-secondary" href="#" onclick="goBack()">Back</a>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="row bg-light border border-light" style="min-height: 500px;">
                <img id="frame" src="" alt="movie image" width="200" />
            </div>
            <div class="row">
                <label for="formFile" class="form-label">Upload Movie Cover</label>
            </div>
            <div class="row">
                <div class="col-6">
                    <input id="formFile" class="form-control" type="file" onchange="preview()" />
                </div>
                <div class="col-6">
                    <button onclick="clearImage()" class="btn btn-primary">Clear</button>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="d-flex align-items-start flex-column h-100">
                <form class="form-horizontal" asp-controller="Admin" asp-action="CreateMovie">
                    <div class="form-group">
                        <label for="movie-title">Title</label>
                        <input id="movie-title" class="form-control" placeholder="Title" name="Title"/>
                        <button type="submit">Submit</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    <script>
        $('#frame').ready(() => {
            $('#frame').hide();
        })

        function goBack() {
            window.history.back()
        }
        function preview() {
            var file = event.target.files[0];
            frame.src = URL.createObjectURL(file);
            $('#frame').show();
        }
        function clearImage() {
            document.getElementById('formFile').value = null;
            frame.src = "";
            $('#frame').hide();
        }


    </script>
}

Moovi/Views/Admin/DetailMovie.cshtml
@model AdminMovieDetailViewModel
@using Moovi.ViewModels

<div>
    <div>
        <h1>@Model.Title</h1>
    </div>
    
    <a  class="link-secondary" asp-action="Index">Back</a>

    <br/>


    <div>
        <p>Create Date : @Model.CreatedDate.ToString("dddd, dd MMMM yyyy")</p>
    </div>

    <div>
        <p>Modify Date : @Model.ModifyDate.ToString("dddd, dd MMMM yyyy")</p>
    </div>

    <br />
    <div>
        <img src="~/assets/blank-image.jpg" alt="Blank image" width="200"/>
    </div>
</div>

Moovi/Views/Admin/Index.cshtml
@using Moovi.ViewModels
@model List<AdminMovieViewModel>
@{
    var adminMovies = Model ?? new List<AdminMovieViewModel>() { };
}
<div class="container">
    <div class="row">
        <h1>Admin</h1>
    </div>
    <div class="row">
        <div class="d-flex flex-row-reverse">
            <a asp-action="UpsertMovie" class="btn btn-primary">New Movie</a>
        </div>
    </div>
    <div class="row justify-content-center py-4">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Image</th>
                    <th scope="col">Title</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int index = 1;
                }
                @foreach (var movie in @adminMovies)
                {
                    <tr>
                        <th scope="row">@index</th>
                        <td>
                            @if (movie.FileName == null || movie.FilePath == null)
                            {
                                <img src="./assets/blank-image.jpg" width="50" height="50" alt="blank image" />
                            }
                            else
                            {
                                <img src="" width="50" height="50" alt="movie-cover" />
                            }
                        </td>
                        <td>@Html.DisplayFor(i => movie.Title)</td>
                        <td>
                            <a class="btn btn-light" asp-route-id="@movie.Id" asp-action="UpsertMovie">Edit</a>
                            <a class="btn btn-light" asp-route-id="@movie.Id" asp-action="DetailMovie">Detail</a>
                            <a class="btn btn-danger" asp-route-id="@movie.Id" asp-action="DeleteMovie">Del</a>
                        </td>
                    </tr>
                    index++;
                }
            </tbody>
        </table>
    </div>
</div>

Moovi/Views/Admin/UpsertMovie.cshtml
@model UpsertMovieViewModel
@using Moovi.ViewModels

<div class="container">
    <div class="row my-4">
        <h1>Create Movie</h1>
        <a class="link-secondary" asp-action="Index">Back</a>
    </div>

    <div class="row">
        <form method="post" class="form-horizontal" enctype="multipart/form-data" asp-controller="Admin" asp-action="UpsertMovie">
            <div>
                <div class="form-group text-center">
                    <div style="min-height: 300px;">
                        <img id="frame" src="~/assets/blank-image.jpg" alt="blank" width="300" />
                    </div>
                    <div class="text-center">
                        <label for="formFile" class="form-label">Upload Movie Cover</label>
                    </div>
                    <div class="d-flex justify-content-center">
                        <div class="py-2">
                            <input asp-for="Formfile" id="formFile" name="Formfile" class="form-control" type="file" onchange="preview()" />
                        </div>
                        <div class="py-2">
                            <a onclick="clearImage()" class="btn btn-primary">Clear</a>
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <div class="d-flex justify-content-center align-items-center">

                        <div class="p-2">
                            <label for="movie-title">Title</label>
                        </div>
                        <div class="p-2">
                            <input asp-for="Title" id="movie-title" class="form-control" placeholder="Title" name="Title" />
                        </div>
                    </div>

                    <div class="text-center">
                        @Html.ValidationSummary()
                    </div>

                    <div class="d-flex justify-content-end">
                        <div>
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </div>
                </div>
            </div>

        </form>

    </div>
</div>

@section Scripts {
    <script>
        function goBack() {
            window.history.back()
        }
        function preview() {
            var file = event.target.files[0];
            frame.src = URL.createObjectURL(file);
        }
        function clearImage() {
            document.getElementById('formFile').value = null;
            frame.src = "~/assets/blank-image.jpg";
        }


    </script>
}

Moovi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Moovi so cool👍</p>
</div>

Moovi/Views/Movie/Index.cshtml
@using Moovi.ViewModels

@model List<MoviesViewModel>
@{
    var movies = Model ?? new List<MoviesViewModel>() { };
}
<div class="container">
    <div class="row">
        <h1>
            Movies
        </h1>
        <br />
    </div>
    <div class="row justify-content-center py-4">
        @foreach (var movie in @movies)
        {
            <div class="col-md-3 px-1">
                <div class="card">

                    @*@if (movie.FileName == null || movie.FilePath == null)
                    {
                        <img class="card-img-top" src="~/assets/blank-image.jpg" alt="blank">
                    }
                    else
                    {
                        <img class="card-img-top" src="@movie.FilePath" alt="@movie.Title" />
                    }*@

                    <img class="card-img-top" src="@movie.FilePath" alt="@movie.Title" />

                    <div class="card-body">
                        <div class="card-title">
                            @Html.DisplayFor(i => movie.FilePath)
                        </div>
                    </div>

                </div>
            </div>
        }
    </div>
</div>

@section Scripts{

}

Moovi/Views/Shared/MovieCover.cshtml
@using Moovi.ViewModels
@model MoviesViewModel
@{
    var movie = Model ?? new MoviesViewModel()
    {
        Id = Guid.Empty,
        Title = ""
    };
}
<div class="card">

    @if (movie.FileName == null || movie.FilePath == null)
    {
        <img class="card-img-top" src="./assets/blank-image.jpg" alt="blank">
    }
    else
    {
        <img class="card-img-top" src="" alt="movie-cover" />
    }

    <div class="card-body">
        <div class="card-title">
            @Html.DisplayFor(i => movie.Title)
        </div>
    </div>

</div>

Moovi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Moovi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Moovi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Moovi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" text-dark asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" text-dark asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Moovi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>